export const priceData= [
    {   title:'Free Tier Pricing',
        price:'Free',
        monthlyActiveUser:'1k',
        customerSupport:'Email',
        productLimit:'100',
        staff:1,
        userSearchRadius:'1 Km',
        inventoryManagement:'-',
        barcodeScanning:'-',
        alexaSkill:'-',
        service:'3',
        customNotificationSupport:'-',
        concurrentOffers:'1',
        comparePricing:'-'
    },
       {title:'Basic Tier Pricing',
        price:'1000 /m/b',
        monthlyActiveUser:'50k',
        customerSupport:'+Whatsapp',
        productLimit:'2.5k',
        staff:5,
        userSearchRadius:'10 Km',
        inventoryManagement:'+',
        barcodeScanning:'-',
        alexaSkill:'-',
        service:'10',
        customNotificationSupport:'-',
        concurrentOffers:'2',
        comparePricing:'-'
    },    {
        title:'Entrepreneur Tire Pricing',
        price:'2500 /m/b',
        monthlyActiveUser:'Unlimited',
        customerSupport:'+Call',
        productLimit:'10k',
        staff:20,
        userSearchRadius:'City',
        inventoryManagement:'+',
        barcodeScanning:'+',
        alexaSkill:'-',
        service:'50',
        customNotificationSupport:'-',
        concurrentOffers:'5',
        comparePricing:'-'
    },
    {   title:'Enterprise Tire Pricing',
        price:'10 /m/b',
        monthlyActiveUser:'Unlimited',
        customerSupport:'+In Person',
        productLimit:'Unlimited',
        staff:'Unlimited',
        userSearchRadius:'City',
        inventoryManagement:'+',
        barcodeScanning:'+',
        alexaSkill:'+',
        service:'Unlimited',
        customNotificationSupport:'+',
        concurrentOffers:'10',
        comparePricing:'+'
    },
]
